name: AxUtils
main: me.Aldreda.AxUtils.AxUtils
depend: [AxUpdater]
softdepend: [Vault,WorldGuard,PlaceholderAPI,Citizens,AxEconomy,AxInventories,ProtocolLib]
version: 1.0
description: Utilities for Aldreda (Started by DMan16)
author: AldredaDevTeam
api-version: 1.16